---
title: "NHL Top 10"
author: "Brandon Chan"
date: "2024-04-16"
output: html_document
---

```{r setup, include=FALSE,}
knitr::opts_chunk$set(echo = FALSE)
```


```{r, include=FALSE}
# install.packages(c('tidyverse', 'caret', 'randomForest', 'xgboost', 'glmnet', 'MASS')) 
library(tidyverse)
```


```{r, include=FALSE}
players<-read_csv("https://raw.githubusercontent.com/BrandonYChan/Hockey-Data/main/skaters.csv")
head(players, 5)
table_info<-read_csv("MoneyPuckDataDictionaryForPlayers.csv")
# table_info
head(players)

```


```{r}
make_barplot<-function(data, x0, y0, color1="orange", color2="coral"){
  xlabel = make_label(deparse(substitute(x0)))
  ylabel = make_label(deparse(substitute(y0))) 
  data %>% 
    ggplot(aes(x=x0, y=reorder(y0, -x0), fill=x0)) + 
    geom_bar(stat="identity") + guides(fill="none") + 
    theme(panel.background = element_rect(fill = "white")) + 
    labs(title=str_glue("2023 Top 10 {xlabel}"), x=xlabel, y=ylabel) + 
    scale_fill_gradient(low=color1, high=color2) + 
    geom_text(aes(label=x0), hjust=1.3)
}

make_label<-function(s){
  s <- s %>% 
        str_to_lower(locale = "en") %>% 
        str_replace_all("_", " ") %>% 
        str_to_title(locale = "en") 
  len<-nchar(s)
  sep<-which(strsplit(s, "")[[1]]=="$")+1
  if(sep>=0){
    s=substring(s, sep, len)
  }
  return(s)
}
```


# Top 10 Scorers 

```{r}
player_goals<- players %>% 
  rename(total_goals = I_F_goals) %>% 
  filter(season==2023 & situation == 'all') %>% 
  select(name, total_goals) %>%
  arrange(desc(total_goals)) %>% 
  slice(1:10)

 make_barplot(player_goals,player_goals$total_goals, player_goals$name, "gold", "brown")

```

# Top 10 Assist Leaders 

```{r}
player_assists<-players %>% 
  mutate(total_assists = I_F_primaryAssists + I_F_secondaryAssists) %>% 
  filter(situation=='all') %>% 
  select(name, total_assists) %>% 
  arrange(desc(total_assists)) %>% 
  slice(1:10)

make_barplot(player_assists, player_assists$total_assists, player_assists$name, "lightgreen", "darkgreen") 
                     
```

# Top 10 Hitters

```{r}
player_hits<-players %>% 
  rename(hits = I_F_hits) %>% 
  filter(situation=='all') %>% 
  select(name, hits) %>% 
  arrange(desc(hits)) %>% 
  slice(1:10)

make_barplot(player_hits, player_hits$hits, player_hits$name, "coral", "red") 


```

# Top 10 Blocked Shot Leaders

```{r}

block_leaders<-players %>% 
  rename(blocks = shotsBlockedByPlayer) %>% 
  filter(situation=="all") %>% 
  select(name, blocks) %>% 
  arrange(desc(blocks)) %>% 
  slice(1:10)

make_barplot(block_leaders, block_leaders$blocks, block_leaders$name, "lightcyan", "cyan")
```

# Top 10 Takeaway Leaders

```{r}
takeaway_leaders<-players %>% 
  rename(takeaways = I_F_takeaways) %>% 
  filter(situation=="all") %>% 
  select(name, takeaways) %>% 
  arrange(desc(takeaways)) %>% 
  slice(1:10)

make_barplot(takeaway_leaders, takeaway_leaders$takeaways, takeaway_leaders$name, "yellow", "orange")
```
